Repository 9taetae9/algorithm-study, pull requests merged in 2025-01, with the labels that each got.

#3 [LeetCode] Is Subsequence - 김태현
  Baekjoon/taehyoun/가장 긴 증가하는 부분 수열.java
  LeetCode/taehyoun/Is Subsequence.java
  Programmers/taehyoun/리코쳇 로봇.java
  SWEA/taehyoun/N-Queen.java
Labels: 제출 완료 ✅

#8 [Programmers] 문자열 나누기 - 김태현
  Programmers/taehyoun/문자열 나누기.java
Labels: 리뷰 요청 💡, 제출 완료 ✅

#12 [Programmers] 문자열 나누기 - 백승헌
  Programmers/seungheon/문자열나누기.java
Labels: 제출 완료 ✅

#15 [Baekjoon] 집합 - 김태현
  Baekjoon/taehyoun/집합.java
Labels: 리뷰 요청 💡, 제출 완료 ✅

#14 [Baekjoon] 집합 - 백승헌
  Baekjoon/seungheon/집합.java
Labels: 제출 완료 ✅

#20 [Silver V] 집합 - 양병운
  Baekjoon/byeongun/집합.java
Labels: 제출 완료 ✅

#16 [Silver V] 집합 - 허지웅
  Baekjoon/jiwoong/집합.java
Labels: 제출 완료 ✅

#21 [Programmers] 석유 시추 - 백승헌
  Programmers/seungheon/석유시추.java
  Programmers/seungheon/충돌위험 찾기.java
Labels: 리뷰 요청 💡, 제출 완료 ✅

#30 [Programmers] 석유 시추 - 김태현
  Programmers/taehyoun/석유 시추.java
Labels: 리뷰 요청 💡, 제출 완료 ✅

#31 [Programmers] 석유 시추 - 양병운
  Programmers/byeongun/석유 시추.java
Labels: 시간 부족 ⏳

#32 [Programmers] 충돌 위험 찾기 - 허지웅
  Programmers/jiwoong/충돌위험찾기.java
Labels: 제출 완료 ✅

#33 [Programmers] 충돌 위험 찾기 - 김태현
  Programmers/taehyoun/충돌 위험 찾기.java
Labels: 제출 완료 ✅

#35 [Programmers] 충돌 위험 찾기 - 양병운
  Programmers/byeongun/충돌위험 찾기.java
Labels: 제출 완료 ✅

#38 [LeetCode] Kth Smallest Element in a BST - 백승헌
  LeetCode/seungheon/Kth Smallest Element in a BST.java
Labels: 제출 완료 ✅

#37 [LeetCode] Kth Smallest Element In A BST - 허지웅
  LeetCode/jiwoong/KthSmallestElementInABST.java
Labels: 제출 완료 ✅

#36 [LeetCode] Kth Smallest Element in a BST - 김태현
  LeetCode/taehyoun/Kth Smallest Element in a BST.java
Labels: 제출 완료 ✅

#41 [LeetCode] Kth Smallest Element in a BST - 양병운
  LeetCode/byeongun/Kth Smallest Element in a BST.java
Labels: 제출 완료 ✅

#42 [Baekjoon] 기타 레슨 - 백승헌
  Baekjoon/seungheon/기타 레슨.java
Labels: 제출 완료 ✅

#48 [Silver I] 기타 레슨 - 조세은/ [Easy] Number of 1 Bits
  Baekjoon/ssen/기타_레슨.java
  LeetCode/ssen/Number of 1 Bits.java
Labels: 지연 제출 ⏰

#47 [LeetCode] Number of 1 Bits - 백승헌
  LeetCode/seungheon/Number of 1 Bits.java
Labels: 제출 완료 ✅

#45 [Baekjoon] 기타 레슨 - 양병운
  Baekjoon/byeongun/기타 레슨.java
Labels: 시간 부족 ⏳

#44 [Baekjoon] 기타 레슨 - 김태현
  Baekjoon/taehyoun/기타 레슨.java
Labels: 제출 완료 ✅

#43 [Baekjoon] 기타 레슨 -허지웅
  Baekjoon/jiwoong/기타 레슨.java
Labels: 제출 완료 ✅

#50 [LeetCode] Number of 1 Bits - 양병운
  LeetCode/byeongun/Number of 1 Bits.java
Labels: 제출 완료 ✅

#51 [ Programmers] 뒤에 있는 큰 수 찾기 - 조세은
  Programmers/ssen/뒤에 있는 큰 수 찾기.java
Labels: 제출 완료 ✅

#53 [Programmers] 뒤에 있는 큰 수 찾기 - 백승헌
  Programmers/seungheon/뒤에 있는 큰 수 찾기.java
Labels: 제출 완료 ✅

#54 [Programmers] 뒤에 있는 큰 수 찾기 - 양병운
  Programmers/byeongun/뒤에 있는 큰 수 찾기.java
Labels: 제출 완료 ✅

#56 [Programmers] 달리기 경주 - 김태현
  Programmers/taehyoun/달리기 경주.java
Labels: 제출 완료 ✅

#58 [Programmers] 달리기 경주 - 백승헌
  Programmers/seungheon/달리기 경주.java
Labels: 제출 완료 ✅

#64 [Programmers] 수레 움직이기 - 양병운
  Programmers/byeongun/수레 움직이기.java
Labels: 지연 제출 ⏰

#62 [Baekjoon] 단지번호붙이기 - 허지웅
  Baekjoon/jiwoong/단지번호붙이기.java
Labels: 제출 완료 ✅

#63 [Baekjoon] 단지번호붙이기 - 김태현
  Baekjoon/taehyoun/단지번호붙이기.java
Labels: 제출 완료 ✅

#67 [Baekjoon] 단지번호붙이기 - 백승헌
  Baekjoon/seungheon/단지번호붙이기.java
Labels: 제출 완료 ✅
